spring:
  application:
    name: bolt
  profiles:
    active: dev
  cloud:
    config:
		allowOverride: true
		failFast: true
		overrideNone: true #覆盖非系统属性　true不覆盖
		overrideSystemProperties: false #覆盖系统属性 false不覆盖
server:
  port: 9003 #应用端口号
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


