spring:
  application:
    name: bolt
  profiles:
    active: dev
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: true
      overrideSystemProperties: true
server:
  port: 9003 #应用端口号
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


