spring:
  application:
    name: bolt
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:7010
      profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


